#!/bin/bash
# build pyGTMx 
# you will need to modify this file according to your system!
# first include is the systems python
# second include is the systems GT.M
# link path is to the system GT.M
# 
gcc -g -c pyGTMx.c -I. -I/usr/include/python2.6 -I/opt/gtm/V53003
gcc pyGTMx.o -o pyGTMx -L/opt/gtm/V53003 -lgtmshr -lc -lpython2.6

